---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project3-userservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice-deployment
  template:
    metadata:
      labels:
        app: userservice-deployment
    spec:
      containers:
      - image: keoffor/user-service:v2
        env:
          - name: VALIDATION
            value: http://$(USER_SERVICE_SERVICE_HOST):8081/users/validate
          - name: EUREKA_URI
            value: http://(EUREKA_SERVICE_SERVICE_HOST):8083/eureka
          - name: ANGULAR_URI
            value: http://20.98.180.247:80
          - name: AWS_ACCESS_KEY
            value: AKIA4OK5FKIY3WZXH4XW
          - name:  AWS_SECRET_KEY
            value: 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
        imagePullPolicy: Always
        name: postservicecontainer
        ports:
        - containerPort: 8081


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: userservice-service
  name: userservice
spec:
  type: LoadBalancer
  ports:
    - name: http-userservice
      port: 8081
      targetPort: 8081
  selector:
    app: userservice-deployment
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
 name: user-service-monitor
spec:
 selector:
   matchLabels:
     app: userservice-service
 endpoints:
   - port: http-userservice
     path: "/actuator/prometheus"
